[package]
name = "utf8-decode"
version = "0.1.0"
authors = ["Stephan Creutz <stephan.cr@gmx.de>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]

[dev-dependencies]
assert_matches = "1.5.0"
